# Launch AWS instance for PCGR cancer reporting
---
- hosts: localhost
  become_method: sudo
  gather_facts: true
  tasks:
    - include_vars: project_vars.yaml
    - name: Launch EC2 instance
      - ec2:
          group: "{{ security_group }}"
          instance_type: "{{ instance_type }}"
          spot_price: "{{ spot_price }}"
          image: "{{ image_id }}"
          keypair: "{{ keypair }}"
          region: "{{ region }}"
          zone: "{{ zone }}"
          count: 1
          wait: yes
          state: present
          volumes:
            - device_name: /dev/xvda
              volume_type: gp2
              volume_size: 250
              delete_on_termination: true
          register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
        # Get rid of SSH "Are you sure you want to continue connecting (yes/no)?" query
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      with_items: "{{ ec2.instances }}"

    - ec2_vol:
        instance: "{{ item.id }}"
        name: my_existing_volume_Name_tag
        device_name: /dev/xvdf
        with_items: "{{ ec2.instances }}"
      register: ec2_vol

    - name: Wait for SSH
        wait_for:
            host: "{{ item.public_dns_name }}"
            port: 22
            delay: 60
            timeout: 320
            state: started
        with_items: "{{ ec2.instances }}"