---
- name: Debug mount devices
  debug:
    msg: "{{ ansible_mounts }}"

- name: Create "{{ pcgr_mount }}" 
  become: true
  file:
    path: "{{ pcgr_mount }}"
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Create ext4 filesystem if not present on external (EBS) volume
  filesystem:
    fstype: ext4
    dev: "{{ volume_device }}"

- name: Mount local work volume
  mount: 
    path: "{{ pcgr_mount }}"
    src: "{{ volume_device }}"
    fstype: ext4 
    state: mounted

- name: Update system and install basics
  become: true
  package: 
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
      - git
      - unzip
      - wget
      - tar
      - gzip
      - bzip2
      - docker.io
      - python-docker
      - tabix
      - nfs-common
      - python-pip
      - python3-pip

- name: Make sure docker-py is installed
  pip:
    name: docker-py
    state: latest

- name: Add SSH keys for UMCCR team
  authorized_key:
    user: ubuntu
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob: "files/public_keys/*.pub"

- name: Add user to docker group
  become: true
  user: name=ubuntu groups=docker append=yes

- name: Pull PCGR docker image
  become: true
  docker_image:
    name: sigven/pcgr:{{ pcgr_release }}

- name: Download and unpack PCGR release
  unarchive:
    src: https://github.com/sigven/pcgr/archive/v{{ pcgr_release }}.tar.gz
    creates: "{{ pcgr_mount }}/pcgr-{{ pcgr_release }}"
    dest: "{{ pcgr_mount }}"
    remote_src: True

- name: Give ubuntu rights to write on "{{ pcgr_mount }}/pcgr-{{ pcgr_release }}"
  become: true
  file:
    path: "{{ pcgr_mount }}/pcgr-{{ pcgr_release }}"
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Creating default PCGR output directory on "{{ pcgr_mount }}/pcgr-{{ pcgr_release }}/output"
  become: true
  file:
    path: "{{ pcgr_mount }}/pcgr-{{ pcgr_release }}/output"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Refresh group info
  become: false
  command: newgrp docker

- name: Setup local firewall
  ufw:
    state: enabled
    rule: allow
    name: OpenSSH
