# Launch AWS instance for PCGR cancer reporting
---
- hosts: localhost
  connection: local
  become_method: sudo
  gather_facts: true
  tasks:
    - include_vars: project_vars.yaml
    - name: Launch EC2 instance
      register: ec2
      local_action:
        module: ec2
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        spot_price: "{{ spot_price }}"
        image: "{{ image_id }}"
        keypair: "{{ keypair }}"
        region: "{{ region }}"
        zone: "{{ zone }}"
        count: 1
        wait: yes
        state: present
    - name: Attach working volume
      local_action: ec2_vol instance={{ item.id }} id={{ volume }} device_name=/dev/xvdf state=present region={{ region }}
      with_items: "{{ ec2.instances }}"
    - name: Add new instance to host group
      local_action:
        module: add_host
        hostname: "{{ item.public_dns_name }}"
        groupname: launched
        # Get rid of SSH "Are you sure you want to continue connecting (yes/no)?" query
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      with_items: "{{ ec2.instances }}"
    - name: Wait for SSH
      local_action: wait_for host={{ item.public_ip }} port=22 state=started
      with_items: "{{ ec2.instances }}"
    - name: Run tasks on recently launched host
      include: tasks/main.yml