# http://superuser.openstack.org/articles/using-ansible-2-0-to-launch-a-server-on-openstack/
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy an instance
      os_server:
        state: present
        auth:
          auth_url: "{{ ostack.auth_url }}"
          username: "{{ ostack.username }}"
          password: "{{ ostack.password }}"
          project_name: "{{ ostack.project }}"
        name: "{{ ostack.hostname }}"
        image: "{{ ostack.image }}"
        key_name: "{{ ostack.keypair }}"
        wait: yes
        flavor: "{{ ostack.flavor }}"
        auto_ip: yes
        network: "{{ ostack.network }}"
        meta:
          hostname: "{{ ostack.hostname }}"

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.server.public_v4 }}"
        groupname: launched
      with_items: "{{ os_instance }}"

    - name: Get rid of SSH "Are you sure you want to continue connecting (yes/no)?" query
      shell: ssh-keyscan "{{ item.server.public_v4 }}" >> $HOME/.ssh/known_hosts
      with_items: "{{ os_instance }}"

- name: Deploy PCGR on OpenStack
  hosts: launched
  become: True
  gather_facts: True
  roles:
    - common
    - hpc
