---
 - name: "Install PCGR"
   hosts: all
   user: ubuntu 
   become: yes
   pre_tasks:
     - raw: sudo apt-get -y install python-simplejson aptitude
       ignore_errors: true
     - action: setup
   roles:
    #- openstack
    #- hpc
    - aws
