---
 - name: "Install PCGR"
   hosts: all
   user: ubuntu 
   sudo: yes
   pre_tasks:
     - raw: sudo apt-get -y install python-simplejson
       ignore_errors: true
     - action: setup
   tasks:
    - include: tasks/main.yml