---
 - name: "Install PCGR"
   hosts: all
   user: ubuntu 
   sudo: yes
   pre_tasks:
     - raw: sudo apt-get -y install python-simplejson aptitude
       ignore_errors: true
     - action: setup
   roles:
    - pcgr_hpc
    #- pcgr_aws
