---
- include_vars: project_vars.yaml

- name: Create ext4 filesystem if not present
  filesystem: fstype=ext4 dev={{ ansible_mounts[1].device }}
  become: true

- name: Mount local work volume
  become: true
  mount: name=/mnt/work src={{ ansible_mounts[1].device }} fstype=ext4 state=mounted

- name: Give ubuntu rights to write on /mnt/work
  become: true
  file:
    path: /mnt/work
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Update system and install basics
  become: true
  package: 
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
      - git
      - unzip
      - wget
      - tar
      - gzip
      - bzip2
      - docker.io
      - python-docker
      - tabix
      - nfs-common

- name: Add SSH keys for UMCCR team
  authorized_key:
    user: ubuntu
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/ohofmann.ssh

- name: Add user to docker group
  become: true
  user: name=ubuntu groups=docker append=yes

- name: Add HPC LDAP group to instance
  group:
    gid: 6034
    name: gx8

- name: Add HPC LDAP user to instance
  become: true
  user:
    uid: 11937
    name: gx8_nfs

- name: Refresh group info
  become: false
  command: newgrp docker

- name: Mount HPC volume
  mount:
    path: /mnt/raijin
    src: gdata3-nfs.nci.org.au:/mnt/gdata3/gx8/data
    fstype: nfs
    opts: hard,fg,defaults,nosuid,exec,ro,noatime,intr,rsize=32768,wsize=32768
    state: mounted

- name: Setup local firewall
  ufw:
    state: enabled
    rule: allow
    name: OpenSSH

- name: Restore tenjin docker state
  notify: stop docker
  unarchive:
    src: /mnt/raijin/data/PCGR/tenjin_docker.tbz2
    dest: /var/lib/docker
    remote_src: yes

- name: Create PCGR data dir
  file:
    path: /mnt/work/pcgr-0.3.4/data
    state: directory

- name: Restore PCGR datapack from HPC filesystem
  notify: restart docker
  unarchive:
    src: /mnt/raijin/data/PCGR/pcgr.databundle.GRCh37.20170420.tgz
    dest: /mnt/work/pcgr-0.3.4/data
    creates: /mnt/work/pcgr-0.3.4/data/.vep
    remote_src: yes

- name: Download and unpack PCGR release
  unarchive:
    src: https://github.com/sigven/pcgr/archive/v0.3.4.tar.gz
    creates: /mnt/work/v*.tar.gz
    dest: /mnt/work
    remote_src: True
